#!/bin/bash

if [[ ! -d ~/bin ]]; then
  mkdir ~/bin
  echo "Verzeichnis ~/bin erstellt."
fi

cp serie ~/bin/serie
chmod +x ~/bin/serie

echo "Lösche Installer"
rm -f serie install README.md && rm -rf .git
cd ..
rmdir serie

echo
echo "serie erfolgreich installiert nach ~/bin/serie"
exit 0
